### ISSUE TITLE
🤗 [REQUEST] - AutoCoder

### ISSUE THREAD

**Issue by ethanc8** [bigcode-project/bigcodebench#10]
### Model introduction

AutoCoder is a very strong coding model family with a code interpreter mode. Its 33B version surpasses GPT-4-Turbo on base HumanEval, and it has generally strong benchmark performance.

Models:
* [based on Deepseek-Coder-33B](https://huggingface.co/Bin12345/AutoCoder)
* [based on Deepseek-Coder-6.7B](https://huggingface.co/Bin12345/AutoCoder_S_6.7B)
* [based on CodeQwen1.5-7B](https://huggingface.co/Bin12345/AutoCoder_QW_7B)

### Model URL

https://huggingface.co/Bin12345

### Author

No

### Security

- [X] I confirm that the model is safe to run which does not contain any malicious code or content.

### Integrity

- [X] I confirm that the model comes from unique and original work and does not contain any plagiarism.

**Comment by terryyz** [comment]
Done.

**Comment by terryyz** [comment]
Link to: https://github.com/evalplus/evalplus/issues/200
