### ISSUE TITLE
🤗 [REQUEST] - ReflectionCoder

### ISSUE THREAD

**Issue by ethanc8** [bigcode-project/bigcodebench#11]
### Model introduction

This model family is based on CodeLlama and DeepSeek Coder, and aims to improve model performance by using feedback from compilation and test cases (like OpenCodeInterpreter) to increase the model's performance in one-off generations. It includes multiple models, and its strongest model, based on DeepSeek Coder 33B, is stronger in EvalPlus benchmarks than any model currently on the EvalPlus leaderboard ([evaluation](https://github.com/evalplus/evalplus/issues/206)). If you have limited evaluation resources, I'd recommend to prioritize the DeepSeek-based models in the model family.

### Model URL

https://huggingface.co/collections/SenseLLM/reflectioncoder-665469339ccb17d967ade0d9

### Author

No

### Security

- [X] I confirm that the model is safe to run which does not contain any malicious code or content.

### Integrity

- [X] I confirm that the model comes from unique and original work and does not contain any plagiarism.

**Comment by terryyz** [comment]
There is no chat template provided in these tokenizer configs. I can only evaluate the direct completion on BCB-complete.

**Comment by ethanc8** [comment]
I'll ask @SenseLLM on HuggingFace then.

**Comment by terryyz** [comment]
Thanks!

**Comment by ethanc8** [comment]
Also, the fine tuning data us publicly available - https://huggingface.co/datasets/m-a-p/CodeFeedback-Filtered-Instruction https://huggingface.co/datasets/SenseLLM/ReflectionSeq-GPT https://huggingface.co/datasets/SenseLLM/ReflectionSeq-DS

**Comment by terryyz** [comment]
Will update on the leaderboard

**Comment by renhouxing** [comment]
Hi @ethanc8 @terryyz , thanks for your attention to our work, I will update the chat template today.
