### ISSUE TITLE
🤗 [REQUEST] - Artigenz-Coder-DS-6.7B

### ISSUE THREAD

**Issue by ethanc8** [bigcode-project/bigcodebench#15]
### Model introduction

The model is a finetune of DeepSeek-Coder-6.7B by the "Artigenz team" (this is currently their only model). They claim that they will release the dataset soon, but no dataset is currently available. It is currently the best DeepSeek-Coder-6.7B finetune on the EvalPlus leaderboard.

### Model URL

https://huggingface.co/Artigenz/Artigenz-Coder-DS-6.7B

### Author

No

### Security

- [X] I confirm that the model is safe to run which does not contain any malicious code or content.

### Integrity

- [X] I confirm that the model comes from unique and original work and does not contain any plagiarism.

**Comment by terryyz** [comment]
Results will be updated shortly.
