### ISSUE TITLE
🤗 [REQUEST] - CodeGeeX-4-9B

### ISSUE THREAD

**Issue by ethanc8** [bigcode-project/bigcodebench#19]
### Model introduction

CodeGeeX-4-9B was finetuned by Tsinghua University from Zhipu AI's GLM-4-9B to be better at code generation. They claim strong performance on BigCode-Bench and other public benchmarks. They [claim that](https://github.com/THUDM/CodeGeeX4) "CodeGeeX4-ALL-9B scored 48.9 and 40.4 for the complete and instruct tasks of BigCodeBench, which are the highest scores among models with less than 20 billion parameters. "

### Model URL

https://huggingface.co/THUDM/codegeex4-all-9b

### Additional instructions (Optional)

More information is available at https://github.com/THUDM/CodeGeeX4.

### Author

No

### Security

- [X] I confirm that the model is safe to run which does not contain any malicious code or content.

### Integrity

- [X] I confirm that the model comes from unique and original work and does not contain any plagiarism.

**Comment by terryyz** [comment]
FYI
https://x.com/terryyuezhuo/status/1810073591129739706?s=46&t=80yert6J2-kaeStiTfFnFg

**Comment by ethanc8** [comment]
We should probably ask the researchers on GitHub or HuggingFace then.

**Comment by terryyz** [comment]
I asked @Stanislas0 to add the chat template via email last week, but I haven't received any reply yet. I may file an issue in their repo.

**Comment by terryyz** [comment]
Results will be updated shortly.

**Comment by ethanc8** [comment]
I don't see the results on the leaderboard currently.

**Comment by terryyz** [comment]
The leaderboard will be updated (w/ a big change) once v0.1.8 is released. I'm working on the last piece.
