### ISSUE TITLE
🤗 [REQUEST] - NTQAI/Nxcode-CQ-7B-orpo

### ISSUE THREAD

**Issue by bino282** [bigcode-project/bigcodebench#22]
### Model introduction

An ORPO fine-tune of Qwen/CodeQwen1.5-7B-Chat on 100k samples ours datasets. The model achieves 86% and 81% on humanval and humaneval plus respectively, surpass GPT-4-Turbo (Nov 2023) on humaneval, top 1 average score on bigcode leaderboard

### Model URL

https://huggingface.co/NTQAI/Nxcode-CQ-7B-orpo

### Additional instructions (Optional)

Let's use the following template for code completion task(example python):
"Complete the following Python function:\n{prompt}"

### Author

Yes

### Security

- [X] I confirm that the model is safe to run which does not contain any malicious code or content.

### Integrity

- [X] I confirm that the model comes from unique and original work and does not contain any plagiarism.

**Comment by terryyz** [comment]
Just a note that the evaluation will be done after the release of `v0.1.8`, which should be around this weekend or next Monday.

**Comment by terryyz** [comment]
Done.

**Comment by bino282** [comment]
where an I check the results? I haven't seen it here yet. https://huggingface.co/spaces/bigcode/bigcodebench-leaderboard

**Comment by terryyz** [comment]
Just updated the leaderboard:
<img width="900" alt="1721566000234" src="https://github.com/user-attachments/assets/88423092-7e7f-4768-a80e-2b8d8f37d9d2">

Compared to CodeQwen, it follows the verbose instructions better.
