### ISSUE TITLE
🤗 [REQUEST] - InverseCoder

### ISSUE THREAD

**Issue by terryyz** [bigcode-project/bigcodebench#26]
### Model introduction

InverseCoder is a series of code LLMs instruction-tuned by generating data from itself through Inverse-Instruct. It is created by Institute of Computing Technology, Chinese Academy of Sciences. More information can be found in [paper](https://arxiv.org/pdf/2407.05700).

https://github.com/evalplus/evalplus/issues/217#issue-2410146145

### Model URL

https://huggingface.co/wyt2000/InverseCoder-CL-7B; https://huggingface.co/wyt2000/InverseCoder-DS-6.7B; https://huggingface.co/wyt2000/InverseCoder-CL-13B

### Author

No

### Security

- [X] I confirm that the model is safe to run which does not contain any malicious code or content.

### Integrity

- [X] I confirm that the model comes from unique and original work and does not contain any plagiarism.

**Comment by terryyz** [comment]
Hi @wyt2000, would you mind adding the `chat_template` to the tokenizer config for the proper evaluation on both Complete and Instruct splits? Thanks!

**Comment by wyt2000** [comment]
> Hi @wyt2000, would you mind adding the `chat_template` to the tokenizer config for the proper evaluation on both Complete and Instruct splits? Thanks!
@terryyz 
Done. Thanks for your reminder.

**Comment by terryyz** [comment]
> @terryyz Done. Thanks for your reminder.

Thanks! I'll evaluate them shortly.

**Comment by terryyz** [comment]
Done
