### ISSUE TITLE
🤗 [REQUEST] - Codestral Mamba

### ISSUE THREAD

**Issue by ethanc8** [bigcode-project/bigcodebench#27]
### Model introduction

This is a Mamba2 model trained by Mistral for coding usecases and instruct-tuned. Its context length is at least 256K tokens.

### Model URL

https://huggingface.co/mistralai/mamba-codestral-7B-v0.1

### Additional instructions (Optional)

It can be run with [TensorRT-LLM's `mamba` example](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/mamba) or with [mistral-inference >= 1.2.0](https://github.com/mistralai/mistral-inference/releases/tag/v1.2.0). It can also be used via API (`codestral-mamba-2407` on la Plateforme, `codestral-mamba` on OpenRouter).

### Author

No

### Security

- [X] I confirm that the model is safe to run which does not contain any malicious code or content.

### Integrity

- [X] I confirm that the model comes from unique and original work and does not contain any plagiarism.

**Comment by terryyz** [comment]
It is on the leaderboard 😄

**Comment by ethanc8** [comment]
I don't see it... Also there are no recent commits to https://github.com/bigcode-bench/bigcode-bench.github.io.

**Comment by terryyz** [comment]
I may forget to update the GP website. You can check https://huggingface.co/spaces/bigcode/bigcodebench-leaderboard for now.

**Comment by terryyz** [comment]
Done.
