### ISSUE TITLE
🤗 [REQUEST] - Mathstral

### ISSUE THREAD

**Issue by ethanc8** [bigcode-project/bigcodebench#29]
### Model introduction

The model is Mistral 7B (unknown whether it's v0.1, v0.2, or v0.3) trained on various math datasets.

### Model URL

https://huggingface.co/mistralai/mathstral-7B-v0.1

### Additional instructions (Optional)

Its inference should be similar to Mistral 7B.

### Author

No

### Security

- [X] I confirm that the model is safe to run which does not contain any malicious code or content.

### Integrity

- [X] I confirm that the model comes from unique and original work and does not contain any plagiarism.

**Comment by terryyz** [comment]
As it is specifically designed for the math capability, I probably will skip this one. I assume that it should be worse than codestral mamba at least.

**Comment by ethanc8** [comment]
Since you are skipping this one, I'll close the issue unless you decide to go back and evaluate it.
