### ISSUE TITLE
Pass@100 not supported?

### ISSUE THREAD

**Issue by JohnLins** [bigcode-project/bigcodebench#50]
Why are the values of k limited to [1,5,10]?

"The "k" includes [1, 5, 10] where k values <= the sample size will be used"

**Comment by terryyz** [comment]
I wasn't aware that users wanted to compute Pass@100. I will include this in the next version! Also feel free to submit a PR on this :)

**Comment by terryyz** [comment]
Now supported with `bigcodebench=v0.2.0`.
