### ISSUE TITLE
[REQUEST] Remove Reflection-Llama-3.1-70B

### ISSUE THREAD

**Issue by wakamex** [bigcode-project/bigcodebench#51]
**Rationale**

It's been proven to be a fraud. Their CEO has repeatedly lied and not fully come clean about:
1. Uploading weights identical to Llama 3
2. Faking API responses using Sonnet and ChatGPT

Sources: 
https://x.com/MaziyarPanahi/status/1838559480658710982
https://x.com/Yuchenj_UW/status/1833627813552992722

The repo referenced in the [request to add Reflection](https://github.com/bigcode-project/bigcodebench/issues/43) has since been deleted.

The [repo that hosts the re-uploaded weights](https://huggingface.co/leafspark/Reflection-Llama-3.1-70B-GGUF) warns the original benchmarks can't be trusted:
![image](https://github.com/user-attachments/assets/b37ba150-9c27-451a-af1d-9a690a8a1725)

The founder now admits the model doesn't work: https://x.com/mattshumer_/status/1842313328166907995

Proof the initial released weights are just LoRa applied to Llama 3: https://www.reddit.com/r/LocalLLaMA/comments/1fb6jdy/reflectionllama3170b_is_actually_llama3/

**Comment by terryyz** [comment]
Completed
