### ISSUE TITLE
How to pass a revision for a HuggingFace model?

### ISSUE THREAD

**Issue by RylanSchaeffer** [bigcode-project/bigcodebench#54]
Several HuggingFace models have revisions. How can I pass a specific revision number, in addition to the HuggingFace model name?

**Comment by terryyz** [comment]
Thanks for the interest! @RylanSchaeffer 
At the moment, the vLLM and HF model loading doesn't really support the `revision` parameter. I'll quickly add the feature this week, along with some minor changes :)

**Comment by RylanSchaeffer** [comment]
I think it does! In another project, I'm using vLLM and it accepts a revision argument.

**Comment by RylanSchaeffer** [comment]
https://docs.vllm.ai/en/stable/models/engine_args.html

**Comment by terryyz** [comment]
Yeah, these frameworks do support the `revision`, but I didn't specifically pass it when initializing the model object.

You can view my recent commit to support the model revision [here](https://github.com/bigcode-project/bigcodebench/commit/c5a22bff708b43698630da8d03dfe5063f52216c).

**Comment by terryyz** [comment]
`bigcodebench==v0.2.1` is out. Please refer to `--revision` inside [ADVANCED_USAGE.md](https://github.com/bigcode-project/bigcodebench/blob/main/ADVANCED_USAGE.md).
