### ISSUE TITLE
[Feature Request] Support for Custom Prompts

### ISSUE THREAD

**Issue by Bonytu** [bigcode-project/bigcodebench#57]
Thank you very much for your contribution to the community—this benchmark is outstanding! However, we have a few questions we'd like to discuss further:

We noticed that, aside from defining the chat template, it’s currently not possible to use a custom prompt for testing. Would you consider, in the future, supporting a feature similar to EvalPlus, **where users can upload their model-generated results for score recording**? If this mode were supported, users would be able to test with custom prompts.

Thank you again for your hard work!

**Comment by terryyz** [comment]
Hi @Bonytu,

Thanks for your interest in BigCodeBench! Could you elaborate on the issue of "it’s currently not possible to use a custom prompt for testing"? 

We do support customized prompts for the instruction and response, as shown [here](https://github.com/bigcode-project/bigcodebench/blob/main/bigcodebench/provider/utility.py#L42-L59). We also document them in [Advanced Usage](https://github.com/bigcode-project/bigcodebench/blob/main/ADVANCED_USAGE.md#optional-arguments). Not sure if this is the feature you need.

**Comment by Bonytu** [comment]
Hi, @terryyz ,
Thank you very much for the timely response. However, using `instruction_prefix` and `response_prefix` is still insufficient for us. We need to modify the code implementation to conduct testing in our preferred way. This raises an issue: **when we need to submit requests to you to test the model's performance, there will be some gaps in our results.** Is there a better way to resolve this? For example, **would it be possible for us to submit our generated model outputs to you for testing?** Many thanks.

**Comment by terryyz** [comment]
Hi @Bonytu,

I just added a [Result Submission](https://github.com/bigcode-project/bigcodebench?tab=readme-ov-file#-result-submission) section. Please send us your outputs and results if you'd like to include your models on our leaderboard.

Regarding the prompt design, I'll consider supporting it in the next version. However, if you've already got a good idea to make it fully flexible, feel free to submit a PR  :)

**Comment by Bonytu** [comment]
Hi @terryyz,
Thanks very much for your help~
