### ISSUE TITLE
Are custom prompts allowed?

### ISSUE THREAD

**Issue by lihaoling** [bigcode-project/bigcodebench#58]
Can we use customized prompt. e.g. like Magicoder when testing HumanEval, the promtp will appear in the INSTRUCTION and RESPONSE respectively.

```python
 instruction = f"""Write a solution to the following problem:
```python
{prompt}
```"""
response_prefix = f"""```python
{prompt}"""
```
[https://github.com/ise-uiuc/magicoder/blob/main/experiments/text2code.py#L60](url)

Also, can we extract the **docstring part of task_prompt** from the complete subset of BigCodeBench and use it as the prompt for the INSTRUCTION and **task_prompt** as the prompt for the RESPONSE?

**Comment by terryyz** [comment]
Hi @lihaoling,

Regarding the customized prompt, please refer to #57.

For the docstring extraction, we provide the `doc_struct` column in [BigCodeBench Data](https://huggingface.co/datasets/bigcode/bigcodebench) and [BigCodeBench-Hard Data](https://huggingface.co/datasets/bigcode/bigcodebench-hard). Hope it helps :-)

**Comment by lihaoling** [comment]
Thank you very much for your response timely!

I have understood the rules for setting up a customized prompt. How can we make sure that our test results match yours after making a `Model Evaluation Request`, can we provide you with a custom prompt or can we submit you a pre-generated solution?

**Comment by lihaoling** [comment]
Thank you very much for your thoughtful help, BigCodeBench is really a great job!!!
