### ISSUE TITLE
Leaderboard uses Active Parameters?

### ISSUE THREAD

**Issue by TomLucidor** [bigcode-project/bigcodebench#59]
So here is the issue: DeepSeek Coder on the graph are noted using its active parameter count (GPU velocity?) rather than total parameter count (VRAM/RAM requirements), which is a bit misleading especially when LLMs will be used on laptops and budget desktops. https://bigcode-bench.github.io/
Are there a way to add another toggle such hat it uses the latter? It is on the HuggingFace leaderboard after all https://huggingface.co/spaces/bigcode/bigcodebench-leaderboard
P.S. Even EvalPlus is like this with the UX https://evalplus.github.io/

**Comment by terryyz** [comment]
Hi @TomLucidor,

I updated the size on [wesbite](https://bigcode-bench.github.io/) to the model parameters. Please let me know if there are any other questions :)

**Comment by TomLucidor** [comment]
Thanks, hope someone better speed-dial EvalPlus and others about it
