### ISSUE TITLE
🤗 [REQUEST] - Phi-3.5-mini-instruct

### ISSUE THREAD

**Issue by TomLucidor** [bigcode-project/bigcodebench#60]
### Model introduction

Yeah since it has already been demoed that Phi-3.1-mini was magical, it might be good to also test the newer version 

### Model URL

https://huggingface.co/microsoft/Phi-3.5-mini-instruct

### Additional instructions (Optional)

The current list of very small and ultra-performant LLMs includes 3.5 so could those versions be tested https://huggingface.co/collections/microsoft/phi-3-6626e15e9585a200d2d761e3

P.S. Qwen does rock ngl

### Author

No

### Security

- [X] I confirm that the model is safe to run which does not contain any malicious code or content.

### Integrity

- [X] I confirm that the model comes from unique and original work and does not contain any plagiarism.

**Comment by terryyz** [comment]
Now it is listed on the full set :-)

**Comment by TomLucidor** [comment]
Thanks man, hope that all these "top models" from other benchmarks can get some press. I wonder if there are ways to simultaneously test the ones the newly come out on multiple benchmarks including MBPP, HumanEval, APPS, and DS-1000, with all their derivatives like EvalPlus and CodeGeeX versions?
