### ISSUE TITLE
🤗 [REQUEST] - Other Phi3 models (e.g. Medium 128K)

### ISSUE THREAD

**Issue by TomLucidor** [bigcode-project/bigcodebench#61]
### Model introduction

Thanks for testing Phi-3.5, but I just realized how Phi-3 proper is better than that, which is odd coming from Microsoft. https://ollama.com/library/phi3/tags

### Model URL

https://huggingface.co/collections/microsoft/phi-3-6626e15e9585a200d2d761e3

### Author

No

### Security

- [X] I confirm that the model is safe to run which does not contain any malicious code or content.

### Integrity

- [X] I confirm that the model comes from unique and original work and does not contain any plagiarism.

**Comment by terryyz** [comment]
The Phi-3 models are on the leaderboard, as shown in the attached screenshot :)
![image](https://github.com/user-attachments/assets/58cf661b-5e5c-4dee-a250-e031ceb5aa78)

**Comment by TomLucidor** [comment]
@terryyz not sure if it is not LeaderBoard scatter plot
