### ISSUE TITLE
🤗 [REQUEST] - <O1 2024-12-17>

### ISSUE THREAD

**Issue by Belzedar94** [bigcode-project/bigcodebench#63]
### Model introduction

New reasoning model from OpenAI

### Model URL

https://openai.com/o1/#chatgpt-pro

### Author

No

### Security

- [X] I confirm that the model is safe to run which does not contain any malicious code or content.

### Integrity

- [X] I confirm that the model comes from unique and original work and does not contain any plagiarism.

**Comment by terryyz** [comment]
Done
