### ISSUE TITLE
🤗 Evaluation - microsoft/wavecoder-ultra-6.7b

### ISSUE THREAD

**Issue by iam-samasif** [bigcode-project/bigcodebench#7]
### Model introduction

The model is created by Microsoft and is used for code generation.

### Model URL

https://huggingface.co/microsoft/wavecoder-ultra-6.7b

### Author

No

### Security

- [X] I confirm that the model is safe to run which does not contain any malicious code or content.

### Integrity

- [X] I confirm that the model comes from unique and original work and does not contain any plagiarism.

**Comment by terryyz** [comment]
Thanks @iam-samasif! Working on this :)

**Comment by terryyz** [comment]
Hi @iam-samasif, the evaluation is done. Please check the leaderboard accordingly :)
